#!/bin/sh
set -e

(
  exec >&2
  echo
  echo "!!! ${DPKG_MAINTSCRIPT_PACKAGE} warning !!!"

  echo "The packages nginx-core, nginx-full, nginx-light, nginx-extras are deprecated."
  echo "Packages no longer distribute the nginx binary and are replaced"
  echo "by a metapackage to keep upgrades smooth."
  echo "Please simply install 'nginx' and 'libnginx-mod-...' modules You need"
  echo "instead of these packages."

)

#DEBHELPER#

exit 0
